---
apiVersion: apps/v1
kind: Deployment143234
metadata:
  name: apresentacao
  namespace: apresentacao
  labels:
    app: apresentacao
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apresentacao
  template:
    metadata:
      labels:
        app: apresentacao
    spec:
      containers:
      - name: apresentacao
        image: paulbouwer/hello-kubernetes:1.10
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent
        env:
        - name: MESSAGE 
          value: "Cluster K3S - KOITOS - 18/09 4.14"
